### PR TITLE
Add coarse-graining example

### PR DESCRIPTION
**Pull request by shinkle-lanl**

### CODE REVIEW

**Comment by lubbersnick** [comment]
Should we just incorporate the pairwise repulsion nodes into the library somewhere? They seem useful, although I do not know if it would work nicely in a multi-species context.

**Comment by shinkle-lanl** [comment]
I hope to adapt it to use for mixtures, so we could hold off on adding it to the library until then.

**Comment by lubbersnick** [comment]
ok, sounds reasonable to me

**Comment by shinkle-lanl** [comment]
@lubbersnick I'm now ready for this to be pulled if you have no other suggestions

**Pull request merged**
