### PR TITLE
Add the documentation and examples for hyperparameter tuning

### PR DESCRIPTION
**Pull request by tautomer**
The doc part is done, but I have not added the full example script yet.

### CODE REVIEW

**Comment by tautomer** [comment]
Apart from some typos here and there (I'm pretty there are plenty of them is the tutorial), the PR should be ready.

Sakib wrote the original sequential script and shared to me, so I think I should give him some credits. What's the best way?

**Comment by lubbersnick** [comment]
This is really cool! re: attribution, feel free to put your names in the docstring for example scripts and also, if you desire, the documentation files. e.g. "Contributed by: person (insitution), person (institution)" or something.

Also, to check for my own understanding, it appears there is not a lot of reason for us to add any functions into hippynn itself, because ray/ax already operate on a fairly black-box level. As such we also don't need to add these as optional dependencies. Is that right?

**Comment by tautomer** [comment]
> This is really cool! re: attribution, feel free to put your names in the docstring for example scripts and also, if you desire, the documentation files. e.g. "Contributed by: person (insitution), person (institution)" or something.

Great. I will for sure add Sakib and me, mainly for him to get the proper credits.

> Also, to check for my own understanding, it appears there is not a lot of reason for us to add any functions into hippynn itself, because ray/ax already operate on a fairly black-box level. As such we also don't need to add these as optional dependencies. Is that right?

You are totally right. Just need some fairly small changes to the existing training scripts. We do not have to add them as the optional dependencies.

**Comment by tautomer** [comment]
@lubbersnick I have fixed some typos and add our names to the scripts and docs, but I could not push the commit due to the LANL internet issue. I will push it once the Internet is back.

**Comment by tautomer** [comment]
Just pushed the commit.

**Review by lubbersnick — APPROVED** [review]

**Comment by tautomer** [comment]
@lubbersnick You have to merge it. I don't have the permission.

**Comment by lubbersnick** [comment]
@tautomer I know 🙃

**Pull request merged**
