### PR TITLE
LAMMPS ML-IAP Interface

### PR DESCRIPTION
**Pull request by Boogie3D**
* Add LAMMPS ML-IAP interface based on the LAMMPS ML-IAP Unified Interface.
  * `hippynn/interfaces/lammps_interface/mliap_interface.py`
  * Inputs: `pair_i`, `pair_j`, `rij`, and `nlocal`
  * Outputs: local atom energies, total energy, and `fij` as gradient of local energy w.r.t `rij`

* Add scripts for training and pickling models on the ANI Aluminum data set and SNAP Indium Phosphide data set.
  * `examples/ani_aluminum_example_multilayer.py` trains a two-interaction layer model on ANI Al data
  * `examples/lammps_train_model_InP.py` trains a model on SNAP InP data
  * `examples/pickle_mliap_unified_hippynn_Al_multilayer.py` pickles an ML-IAP Unified HIP-NN two-interaction layer model trained on ANI Al data
  * `examples/pickle_mliap_unified_hippynn_Al.py` pickles an ML-IAP Unified HIP-NN model trained on ANI Al data
  * `examples/pickle_mliap_unifeid_hippynn_InP.py` pickles an ML-IAP Unified HIP-NN model trained on SNAP InP data

(Note: the ML-IAP Unified Interface is not yet merged into the LAMMPS codebase.)

### CODE REVIEW

**Comment by lubbersnick** [comment]
Looking really great! Let's move the lammps examples to a new folder, examples/lammps/ , and let's also provide the input scripts for lammps to show how that works.

**Comment by lubbersnick** [comment]
Also, we should add a new documentation file for running with lammps and describe the procedure

**Comment by Boogie3D** [comment]
Lammps example scripts moved to [examples/lammps/](https://github.com/Boogie3D/hippynn/tree/26b75ca5ebbb3952c32176597a70bc7fdfb9b5ed/examples/lammps) and MLIAP Unified example documentation added [here](https://github.com/Boogie3D/hippynn/blob/26b75ca5ebbb3952c32176597a70bc7fdfb9b5ed/docs/source/examples/mliap_unified.rst).

**Comment by lubbersnick** [comment]
Looking good for now, can think of some minor improvements to the system for the future, but it all seems to work right.

**Pull request merged**
